version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ~/.aws:/root/.aws
    environment:
      - PYTHONPATH=/app
      - UVICORN_RELOAD=true
      - APP_ENV=development
      - AWS_PROFILE=default
    env_file:
      - .env.development

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - APP_ENV=development
