version = 0.1
[default.deploy.parameters]
stack_name = "crypt-trader-bot"
resolve_s3 = true
s3_prefix = "crypt-trader-bot"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
